### ISSUE TITLE
Top Down Shooter Add On Beta

### ISSUE THREAD

**Issue by adriancabouli** [wesleywh/EasyMultiplayer-Invector#12]
First Add Invector TopDownShooter Addon by default.

Then need to add Custom files, and inside BasicNeworkCalls add in with #Region TopDownShooter functions and variables.

After that see how to access or modify ShooterNetworkCalls to be public: Actually i modifed to set it:
inside Mp_vShooterMeleeInput.cs  "public ShooterNetworkCalls nc = null;" instead of protected, but have no idea how to access by otherway

After that replace new custom input and custom controller instead of mp_vthirdpersoncontroller and mp_vThirdPersoninput 

### **Inside Invector components:**
Add ShooterCursor, as TopDownShooter uses in prefab (in this case using the scene prefab is already inserted).
Replace Mp_vTopdownshooterThrowManager instead of default mp_ThrowManager inside player.

_MP_vTopDownShooterMeleeController is the prefab that contains all new updated files with current setups:_

1. CustomController inside Layers tab has Thm var that is throwManager type that need to be seted with throwManager, this is necessary because is called inside BasicNetwork Calls new #region  Topdownshooter.
2. Inside CustomInput TopDown Tab: Ways aim Current Inventory var must be set to intentory_UI, this is for  avoid a bug that if you enter to inventory and press escape, or either press escape in any situation (screen lost focus) and cursor get crazy.

------------------------------------------------------------------

Use the MAIN_TEST_DEMO Scene to test it!, 

Check that camera setup is different to default thirdperson setup, also aimCanvas._

**Comment by wesleywh** [comment]
I was able to get this implemented by adding custom symbols and taking advantage of the BasicNetworkCalls component. I also added the new MP_vTopDownController component. I plan on making a custom package to be included in the next release for TopDown support. 

If you want to include EMI support for top-down then just import the package. Full documentation will be included. 

I still need to test this with the MeleeNetworkCalls and the ShooterNetworkCalls to see if I need to include more symbols into those scripts as well. However, I'm marking this as completed pending further tests. This will be released as part of the `v0.4.0` release of the base packages. Not ETA on it yet but if I get no more errors then probably in the next few days. If I get errors probably another week worth of testing.

Your scripts really helped me narrow down exactly what was needed. Thank you for including them!
