### ISSUE TITLE
Error after switch from Host mode on to off, and rebuild

### ISSUE THREAD

**Issue by adriancabouli** [wesleywh/EasyMultiplayer-Invector#17]
If you change host mode, and recompile, a lot of errors are throw.

![image](https://user-images.githubusercontent.com/2046562/167695195-488ba545-7ae1-49f6-949a-a7b24ab954bd.png)

**Comment by wesleywh** [comment]
Fixed "FilesUtil" parser to account for additional `#endif` and `#if` code blocks. 

Fix will be available in `0.4.1`+ of the base packages
