### ISSUE TITLE
Multiplayer support for vAnimatorEventReceiver and vGenericAnimation

### ISSUE THREAD

**Issue by haytham47** [wesleywh/EasyMultiplayer-Invector#22]
**Feature Description**
-vAnimatorEventReceiver and vGenericAnimation are widely used in invector templates, as it allows to implement alot of cool actions in games like special talents, skills and other actions and events that already hooked to an event in specific animation.
-It was also Supported in the previous multiplayer package (PUN2).

**Comment by wesleywh** [comment]
I posted a code snippet in the #emi-chat on how this can be done. I'm also going to include this in the next release.
