### ISSUE TITLE
StandBuild run server error

### ISSUE THREAD

**Issue by orangeagain** [wesleywh/EasyMultiplayer-Invector#25]
**Describe the bug**
Can't run server on build

**To Reproduce**
run  MAIN_Shooter_NoInventory scene in stand build 
Start host or start server
will stack on below screen

**Screenshots/YouTube Links**
![20220531-172307](https://user-images.githubusercontent.com/12761984/171142686-3797704f-f59b-4310-b975-49427c0cacf1.png)

**Versions**
 - OS: m1 Macos
 - Unity Version 2021.3.1f1c1
 - Invector Version Latest
 - EMI Package - shooter
 - EMI Version Latest

**Additional context**

**Comment by wesleywh** [comment]
This could literally be anything and highly doubt this is a bug on my side.

In your version listing what does "latest" mean? Can I get more specific versions? Pictures of your emi network manager setup? Character used? Scenes travel to used? I do not have a lot to go off of here.

**Comment by orangeagain** [comment]
> This could literally be anything and highly doubt this is a bug on my side.
> 
> In your version listing what does "latest" mean? Can I get more specific versions? Pictures of your emi network manager setup? Character used? Scenes travel to used? I do not have a lot to go off of here.

Invector version: 2.6.2
EMI version: 0.4.2a
thanks

**Comment by orangeagain** [comment]
Still on "EMI 0.4.3" with "invector 2.6.2a"

**Comment by wesleywh** [comment]
I have verified that this is working just fine with invector 2.6.2. Check your settings. I'll be upgrading to "2.6.2a" tracked on this ticket here: https://github.com/wesleywh/EasyMultiplayer-Invector/issues/23

This can often happen if you fail to make a connection. Could be any number of things. If testing locally, one of the most common reasons for this is firewalls or antivirus.

Be sure to also take advantage of the verbose logging available on the network manager to help you debug.

Could also be a result of you not enabling "hosted mode" and attempting to run a hosted mode build.
