### ISSUE TITLE
Null Error on other clients when one leaves (Alt f4)

### ISSUE THREAD

**Issue by MotasemZakarneh** [wesleywh/EasyMultiplayer-Invector#4]
**Describe the bug**
upon one of the clients leaving leaving by pressing (alt + f4) on his client, i get this
this was made using the melee no inventory demo

**To Reproduce**
1.Hosted Mode no inventory demo duplicated scene
2.Players Join
3.A Client Presses Alt F4
4.In the editor (host) we can see this error 

**Expected behavior**
No null error on remaining clients

**Screenshots/YouTube Links**
![image](https://user-images.githubusercontent.com/46475130/161475459-0c8c3d01-925d-4997-b941-59483d61dfc8.png)

**Versions**
 - OS: Windows
 - Unity Version 2019.4
 - Invector Version [e.g. 2.6.1b]
 - EMI Package - FullSuite
 - EMI Version 0.3.4
- Mirror Version 65.0.0

**Comment by wesleywh** [comment]
Has this been attempted on the most recent release (`0.3.4`)? I was unable to replicate this on the most recent version. Feel free to re-open this issue if you are still having issues with the most recent release.

I attempted this with hosted mode via unity editor and a build dedicated server. Had the server running, connected the client, pressed Alt+F4 on the client and the client disconnected from the server without issue. Not errors were displayed either with the dedicated server or the hosted mode server.

**Comment by MotasemZakarneh** [comment]
i created a small video for this case, i'll do a bit more testing i guess
https://youtu.be/6eoNjtFtUi0

**Comment by MotasemZakarneh** [comment]
upon further investigation i added few debug messages
```
ClientConnection conn = ClientUtil.GetClientConnection(gameObject);
                if (conn)
                {
                    Debug.Log(name);
                    Debug.Log(GetComponent<NetworkIdentity>());
                    Debug.Log(GetComponent<NetworkIdentity>().connectionToClient);
                    Debug.Log(conn.gameObject);
                    NetworkServer.ReplacePlayerForConnection(GetComponent<NetworkIdentity>().connectionToClient, conn.gameObject, true);
                }
```

and this was the result on the host

![image](https://user-images.githubusercontent.com/46475130/161879619-58ffd0ed-2f60-4c96-9039-c433213f613c.png)

unsure, what it is but i am theorizing a bit and here is what i think:

i think what is happening is that, once the player hits Alt + F4, the OnDestroy Gets Called
and then this function
`ClientConnection conn = ClientUtil.GetClientConnection(gameObject);`
manages to find the ClientConnection game object, the same ClientConnection Game object that is about to be destroyed

then `NetworkServer.ReplacePlayerForConnection` gets called which attempts to replace the Player but it uses as arguments the 
`GetComponent<NetworkIdentity>().connectionToClient` and `conn.gameObject`

and the conn.gameObject is already the owne  of the connection

then 
```
            if (keepAuthority)
                // This needs to be sent to clear isLocalPlayer on
                // client while keeping hasAuthority true
                SendChangeOwnerMessage(previousPlayer, conn);
```


gets called in NetworkServer.cs 
and the `previousPlayer` is probably null, 

```
internal static void SendChangeOwnerMessage(NetworkIdentity identity, NetworkConnectionToClient conn)
        {
            // Don't send if identity isn't spawned or only exists on server
            if (identity.netId == 0 || identity.serverOnly) return;//breaks here
```
which makes the game break in the SendChangeOwnerMessage
since, there is really no new player, the ClientUtil.GetClientConnection i assume is grabbing the same game object

**Comment by wesleywh** [comment]
Does this issue still occur on Mirror `v55.3.8`? I know that is a older version of mirror but I have yet to verify functionality with the newer versions of Mirror. It will be safer for you to use my suggested version instead of `65.0.0`

**Comment by MotasemZakarneh** [comment]
> Does this issue still occur on Mirror `v55.3.8`? I know that is a older version of mirror but I have yet to verify functionality with the newer versions of Mirror. It will be safer for you to use my suggested version instead of `65.0.0`

ok, so this appears to be something with the newer versions of mirror, they apparently changed things under the hood that are related to the player (OnClientConnect creates the player, and there is NetworkConnectionToClient instead of NetworkConnection, a whole lot of nice changes)
not sure how to fix it as i don't want to modify the core scripts of the mirror, nor the EMI, so i guess i'll just wait a bit and hope the EMI gets to an updated version of mirror at some point.

(honestly, the newer version has some really nice features so i hope it is updated at some point).

**Comment by wesleywh** [comment]
Will close for now as this is with the newer version of Mirror which this project doesn't currently support. Might re-visit this when I will do an upgrade on the Mirror version.
