### ISSUE TITLE
Need the hit marker and directional damage indicator in UI of EMI 

### ISSUE THREAD

**Issue by AmmarTee** [wesleywh/EasyMultiplayer-Invector#6]
Hello Wesley,

a. We are looking forward to seeing a UI indicator for hir confirmation marker with a sound effect 
b. A Directional damage indicator when you receive damage is what we would like to have in the EMI's next version

**Comment by wesleywh** [comment]
This has been built and will be available as part of the next release of the UI package. Also works in combination with team based mechanics.
